# fly.toml app configuration file generated for bloglistmadness on 2025-01-19T17:11:45+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bloglistmadness'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services.script_checks]]
  command = "/app/health_check.sh"
  grace_period = "10s"
  interval = 10000
  restart_limit = 0
  timeout = 1000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
